### ISSUE TITLE
No depth image

### ISSUE THREAD

**Issue by robotlearning123** [NVlabs/UnseenObjectClustering#1]
Hi, thanks for your great project! 

When I o run the code, there are some problems I am sure.

1. For ros example, when I run `roslaunch realsense2_camera rs_aligned_depth.launch tf_prefix:=measured/camera`, there is no message in topic `/camera/aligned_depth_to_color/image_raw`. When I change the launch file to `roslaunch realsense2_camera rs_camera.launch align_depth:=true tf_prefix:=measured/camera`, the topic works fine. (P.S.: I use a intel realsense D435i camera)
2. Due to the ROS python2 version, there maybe some problems. For the `tf` import problem, [this issue](https://github.com/ros/geometry2/issues/259) maybe helps. When I run `./experiments/scripts/ros_seg_rgbd_add_test_segmentation_realsense.sh $GPU_ID`, I got error like this:
```bash
[ERROR] [1610543855.033907]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7f8338747dd8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/message_filters/__init__.py", line 75, in callback
    self.signalMessage(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/message_filters/__init__.py", line 57, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/message_filters/__init__.py", line 282, in add
    for vv in itertools.product(*[zip(*s)[0] for s in stamps]):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/message_filters/__init__.py", line 282, in <listcomp>
    for vv in itertools.product(*[zip(*s)[0] for s in stamps]):
TypeError: 'zip' object is not subscriptable
```
For now, I only rebuild tf package with python3 env. So could you point out which part runs based on ros python2 or rebuilds with  python3? Thanks a lot!
3. I am not sure the camera name [here](https://github.com/NVlabs/UnseenObjectClustering/blob/14fcf4ff72b4e01591df07fd8434168d371ff983/ros/test_images_segmentation.py#L67). `D415` or `D435`?

Thanks a lot!

**Comment by robotlearning123** [comment]
When I change the python environment to anaconda2, it works.
