### ISSUE TITLE
Run with ROS

### ISSUE THREAD

**Issue by AmanuelErgogo** [NVlabs/UnseenObjectClustering#10]
Hi, @bearpaw 
thanks for this great contribution.

I have created a conda environment with python 2.7 and successfully installed all the requirements and I already have ros noetic. When I try to run the ros node using 
`./experiments/scripts/ros_seg_rgbd_add_test_segmentation_realsense.sh $GPU_ID`

I get this error:-

`Traceback (most recent call last):
  File "./ros/test_images_segmentation.py", line 13, in <module>
    import tf
  File "/opt/ros/noetic/lib/python3/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define init function (init_tf2)`

I guess this occurs because of the python version that ROS noetic uses(python3). So, how do I run on Ubuntu 20.04 with ROS noetic?

**Comment by AmanuelErgogo** [comment]
The issue is resolved and was caused by python-pcl lib support in python3.8, conda env on ubuntu 20.04. it's resolved by creating conda env with python3.6.
